config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :products
  end
  root "products#index"
  resources :products do
    member do
      post :add_to_cart

    end

  end
  resources :carts do
    collection do
      delete :all_delete
      post :checkout
    end
  end
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.save
  end
  def total_price
    sum = 0
    self.cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.product.price
      end
    end
    sum
  end

  def dkx_clean!
    self.cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  total      :integer          default(0)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ApplicationRecord
  before_create :dkx_token
  belongs_to :user
  has_many :product_lists

  def dkx_token
    self.token = SecureRandom.uuid
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  price       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string
#

class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
  mount_uploader :image, ImageUploader
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  is_admin               :boolean          default(FALSE)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  def admin?
    is_admin
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end

  end

  def edit
    @product = Product.find(params[:id])

  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/", alert: "You are not admin."
    end
  end
  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  private

  def find_cart
    cart = Cart.find_by(id: session[:cart_id])

    if cart.blank?
      cart = Cart.create
    end
    session[:cart_id] = cart.id
    return cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def all_delete
    # current_cart.cart_items.delete_all
    # current_cart.delete
    current_cart.dkx_clean!
    redirect_to :back
    flash[:notice] = "以全部清空"
  end

  def destroy
    cart_item = current_cart.cart_items.find_by(product_id: params[:id])
    cart_item.destroy
    redirect_to :back
    flash[:notice] = "#{cart_item.product.title}已被删除"
  end

  def checkout
    @order = Order.new
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @order = current_user.orders.new
    @order.total = current_cart.total_price

    if @order.save
      current_cart.cart_items.each do |cart_item|
        product_list = @order.product_lists.new
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.image = cart_item.product.image
        product_list.save
      end
      redirect_to order_path(@order.token)
    else
      render :'carts/checkout'
    end

  end
  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.cart_items.each do |cart_item|
      if cart_item.product.title == @product.title
        flash[:notice] = "#{@product.title}已经存在购物车中"
        return redirect_to :back

      end
    end
    current_cart.add_product_to_cart(@product)
    flash[:notice] = "成功加入购物车"
    redirect_to :back
    # flash[:notice] = "测试加入购物车"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def render_cart_total_price(cart)

    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>
<%= simple_form_for [:admin, @product] do |f|%>
  <div class="group">
    <%= f.input :title %>
  </div>
  <div class="group">
    <%= f.input :description %>
  </div>
  <div class="group">
    <%= f.input :price %>
  </div>
  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <%= f.submit "Submit", data:{disable_with: "Submitting..."}%>

<% end %>

app/views/admin/products/index.html.erb
<h2>Product List</h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to "新增产品", new_admin_product_path, class: "btn btn-primary btn-sm"%>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Opions </th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product|%>
    <tr>
      <td><%= product.id%></td>
      <td>
        <%= link_to product_path(product) do %>
          <% if product.image.present? %>
            <%= image_tag(product.image.thumb.url, class: "thumbnail")%>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= product.title %>
      </td>
      <td><%= product.price %></td>
      <td><%= link_to "Edit", edit_admin_product_path(product) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2>New Product</h2>
<%= simple_form_for [:admin, @product] do |f| %>
  <div class="group">
    <%= f.input :title %>
  </div>
  <div class="group">
    <%= f.input :description %>
  </div>
  <div class="group">
    <%= f.input :price %>
  </div>
  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <%= f.submit "Submit", data: {disable_with: "Submitting..."}%>

<% end %>

app/views/carts/checkout.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>购物明细</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>商品明细</th>
          <th>名称</th>
          <th>单价</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <% if cart_item.product.image.present? %>
                <%= link_to product_path(cart_item.product) do %>
                  <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail")%>
                <% end %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic",class: "thumbnail")%>
              <% end %>
            </td>
            <td><%= cart_item.product.title %></td>
            <td><%= cart_item.product.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="total clearfix">
      <span class="pull-right">
        总计 <%= render_cart_total_price(current_cart)%> CNY
      </span>
    </div>
    <div class="checkout clearfix">
      <%= link_to "生成订单", orders_path(@order), method: :post, class: "btn btn-lg btn-danger pull-right"%>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2> 购物车 </h2>
    <div class="pull-right">
      <%= link_to "清空购物车", all_delete_carts_path, :method => :delete, class: "btn btn-default",
      style: "text-decoration: underline;", data: {confirm: 'Are you sure?'}%>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">商品咨询</th>
          <th>单价</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.cart_items.each do |cart_item| %>
        <tr>
          <td>
            <% if cart_item.product.image.present? %>
              <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail")%>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic",class: "thumbnail")%>
            <% end %>
          </td>
          <td>
            <%= link_to cart_item.product.title, product_path(cart_item.product)%>
          </td>
          <td>
            <%= cart_item.product.price %>
          </td>
          <td>
            <%= link_to "删除", cart_path(cart_item.product_id), method: :delete, class: "btn btn-danger" %>
          </td>
        </tr>

        <% end %>
      </tbody>
    </table>
    <br>
    <div class="total clearfix">
      <span class="pull-right">
        <span>总计  <%= render_cart_total_price(current_cart) %>  RMB</span>
      </span>
    </div>
    <hr>
    <div class="checkout clearfix">
      <%= link_to "确认结账", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right"%>
    </div>
  </div>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 dkx-app
        <br>Design by dkx1982

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">dkx-app </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Product", products_path %></li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to carts_path do %>
                  购物车 <i class="fa fa-shopping-cart"></i>(<%= current_cart.products.count %>)
                <% end %>
              </li>
              <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to(content_tag(:i, "登入", class: 'fa fa-sign-in'), new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <% if current_user.admin? %>
                        <li><%= link_to "Admin 选单", admin_products_path %></li>
                      <% end %>
                        <li> <%= link_to(content_tag(:i, "登出", class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DkxApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar"%>
      <%= render "common/flashes"%>
      <%= yield %>
    </div>
      <%= render "common/footer"%>
  </body>
</html>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>订单明细</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>商品明细</th>
          <th>名称</th>
          <th>单价</th>
        </tr>
      </thead>
      <tbody>
        <% @product_lists.each do |product| %>
          <tr>
            <td>
              <% if product.image.present? %>
                <%= link_to product_path(product) do %>
                  <%= image_tag(product.image.thumb.url, class: "thumbnail")%>
                <% end %>
              <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic",class: "thumbnail")%>
              <% end %>
            </td>
            <td><%= product.product_name %></td>
            <td><%= product.product_price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="total clearfix">
      <span class="pull-right">
        总计 <%= @order.total %> CNY
      </span>
    </div>
    <div class="checkout clearfix">
      <%= link_to "生成订单", "#{}", method: :post, class: "btn btn-lg btn-danger pull-right"%>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to product_path(product) do %>
        <% if product.image.present? %>
          <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
        <% end %>
      <% end %>
      <%= product.title %> ¥ <%= product.price %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.image.present? %>
      <%= image_tag(@product.image.medium.url, class: "thumbnail")%>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail")%>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2><%= @product.title %></h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div class="product-price">
      ¥ <%= @product.price %>
    </div>
    <div class="pull-right">
      <%= link_to "加入购物车", add_to_cart_product_path(@product), :method => :post , :class => "btn btn-primary btn-lg btn-danger" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Hello World!!</h1>